import { HomeContent } from "@/lib/types";

export const home: HomeContent = {
  role: "Product Designer",
  bio: "Продуктовый дизайнер с 4 годами опыта в fintech и e-commerce, сейчас — Team Lead UX/UI в Rentag. Проектирую цифровые продукты от исследования пользовательских проблем до запуска, связывая UX-решения с бизнес-метриками.",
  ctaLabel: "Обсудим?",
  sectionsNav: { projects: "Проекты", about: "Обо мне" },
  viewCase: "Перейти",
  timelineLabel: "Timeline",
  usersLabel: "Users",
  projects: [
    {
      slug: "fintrack",
      title: "Fintrack",
      tag: "Fintech",
      description: "Разработка дизайна iOS-приложения",
      image: "/images/home/fintrack-card-v2.png",
      category: "product",
      available: true,
      timeline: "2025",
      users: "144k",
    },
    {
      slug: "rentag",
      title: "Rentag",
      tag: "Fintech",
      description: "Спроектировал escrow-механику для B2B строительного маркетплейса",
      image: "/images/home/rentag-card.png",
      category: "product",
      available: true,
      timeline: "2026",
      users: "370k",
    },
    {
      slug: "7pr",
      title: "7 Prudov dev",
      tag: "Proptech",
      description: "Создание ключевых экранов для сервиса и поддержка дизайн-системы",
      image: "/images/home/7pr-card-v2.png",
      category: "product",
      available: true,
      timeline: "2025",
    },
    {
      slug: "vodokachka",
      title: "VODOKACHKA",
      tag: "Foodtech",
      description: "0 → 1: разработка сервиса для заказа еды в баре",
      image: "/images/home/vodokachka-card.png",
      category: "product",
      available: true,
      timeline: "2025",
    },
  ],
  about: {
    heading: "Обо мне",
    bio: [
      "Я занимаюсь продуктовым дизайном больше трёх лет, в основном работал с финтехом, инвестициями и разными цифровыми сервисами. Мне важно, чтобы интерфейс реально помогал пользователям и решал задачи бизнеса. Поэтому в работе я всегда опираюсь на исследования и аналитику.",
      "Кроме дизайна, большую часть моей жизни занимает музыка. Я играю на гитаре уже более одиннадцать лет: выступал на сцене, преподавал, а сейчас развиваю свой музыкальный проект. Музыка научила меня дисциплине, умению работать с аудиторией и помогать творческим идеям укладываться в чёткую структуру.",
      "Ещё одно моё увлечение — японские автомобили. Мне нравится разбираться в том, как устроена техника, и заниматься машинами самостоятельно. Сейчас я восстанавливаю и дорабатываю свою некро-тойоту. В этом процессе мне интересны инженерные решения и то, как из отдельных деталей собирается работающая система.",
      "Мне кажется, что у хорошего дизайна, музыки и инженерии много общего. Везде нужно внимание к мелочам, понимание людей и желание сделать сложные вещи простыми и удобными.",
    ],
    contactHeading: "Связь со мной",
  },
  contactTitle: "Открыт к сотрудничеству и новым проектам",
  comingSoon: "Скоро",
};
