import { HomeContent } from "@/lib/types";

export const home: HomeContent = {
  role: "Product Designer",
  bio: "Product designer with 4 years of experience in fintech and e-commerce, currently Team Lead UX/UI at Rentag. I design digital products from user research to launch, tying UX decisions to business metrics.",
  ctaLabel: "Let's talk?",
  sectionsNav: { projects: "Projects", about: "About" },
  viewCase: "View case",
  timelineLabel: "Timeline",
  usersLabel: "Users",
  projects: [
    {
      slug: "fintrack",
      title: "Fintrack",
      tag: "Fintech",
      description: "Development of iOS application design",
      image: "/images/home/fintrack-card-v2.png",
      category: "product",
      available: true,
      timeline: "2025",
      users: "144k",
    },
    {
      slug: "rentag",
      title: "Rentag",
      tag: "Fintech",
      description: "Designed escrow mechanics for a B2B construction marketplace",
      image: "/images/home/rentag-card.png",
      category: "product",
      available: true,
      timeline: "2026",
      users: "370k",
    },
    {
      slug: "7pr",
      title: "7 Prudov dev",
      tag: "Proptech",
      description: "Creating key screens for the service and supporting the design system",
      image: "/images/home/7pr-card-v2.png",
      category: "product",
      available: true,
      timeline: "2025",
    },
    {
      slug: "vodokachka",
      title: "VODOKACHKA",
      tag: "Foodtech",
      description: "0 → 1: building a food ordering service for a bar",
      image: "/images/home/vodokachka-card.png",
      category: "product",
      available: true,
      timeline: "2025",
    },
  ],
  about: {
    heading: "About me",
    bio: [
      "I've been working in product design for over three years, mostly with fintech, investment, and various digital services. It matters to me that an interface actually helps users and solves real business problems. I always lean on research and analytics in my work.",
      "Besides design, music takes up a big part of my life. I've been playing guitar for more than eleven years: performed on stage, taught lessons, and now I'm building my own music project. Music taught me discipline, how to work with an audience, and how to fit creative ideas into a clear structure.",
      "Another thing I'm into is Japanese cars. I like understanding how the mechanics work and doing the wrenching myself. Right now I'm restoring and upgrading my beat-up old Toyota. What interests me in that process is the engineering — how a working system comes together out of individual parts.",
      "I think good design, music, and engineering have a lot in common. All three need attention to detail, an understanding of people, and a drive to make complicated things simple and usable.",
    ],
    contactHeading: "Get in touch",
  },
  contactTitle: "Open to collaboration and new projects",
  comingSoon: "Coming soon",
};
